# Generated by Django 5.1.4 on 2024-12-20 22:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=99)),
                ('title', models.CharField(max_length=99)),
                ('content', models.TextField()),
                ('published_date', models.DateField()),
            ],
        ),
    ]
