# Generated by Django 5.1.4 on 2024-12-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=99)),
                ('title', models.CharField(max_length=99)),
                ('subtitle', models.CharField(max_length=99)),
                ('content', models.TextField()),
                ('published_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
