# Generated by Django 5.1.4 on 2024-12-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(default='subtitle', max_length=99),
            preserve_default=False,
        ),
    ]
